version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "Installing dependencies..."
      - npm ci
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test || true
  build:
    commands:
      - echo "Packaging Lambda function..."
      - npm install --production
      - zip -r function.zip . -x '*.git*' -x '*.zip' -x 'node_modules/.cache/*' -x '*.md' -x '.github/*' -x 'cloudformation/*' -x '*.test.js' -x '.eslintrc*'
      - echo "Determining environment from branch..."
      - export BRANCH_NAME=${CODEBUILD_SOURCE_VERSION#refs/heads/}
      - echo "Branch: $BRANCH_NAME"
      - '[ "$BRANCH_NAME" = "main" ] && export ENVIRONMENT=prod || ([ "$BRANCH_NAME" = "develop" ] && export ENVIRONMENT=staging || export ENVIRONMENT=dev)'
      - echo "Environment: $ENVIRONMENT"
      - echo "Verifying AWS credentials..."
      - aws sts get-caller-identity || echo "Warning: Could not verify AWS credentials"
      - echo "Deploying CloudFormation stack..."
      - aws cloudformation deploy --template-file cloudformation/template.yaml --stack-name eventsquid-private-api --parameter-overrides Environment=${ENVIRONMENT} VpcId=${VPC_ID} SubnetIds=${SUBNET_IDS} MongoSecretName=${MONGO_SECRET_NAME} MongoDbName=${MONGO_DB_NAME} --capabilities CAPABILITY_NAMED_IAM --region ${AWS_REGION}
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name eventsquid-private-api --zip-file fileb://function.zip --region ${AWS_REGION}
      - echo "Updating Lambda function configuration..."
      - aws lambda update-function-configuration --function-name eventsquid-private-api --environment Variables="{NODE_ENV=${ENVIRONMENT},MONGO_SECRET_NAME=${MONGO_SECRET_NAME},MONGO_DB_NAME=${MONGO_DB_NAME}}" --region ${AWS_REGION}
artifacts:
  files:
    - function.zip
    - '**/*'

