AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pipeline for eventsquid-api-private Lambda deployment'

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub repository owner
  
  GitHubRepo:
    Type: String
    Description: GitHub repository name
    Default: eventsquid-api-private
  
  GitHubBranch:
    Type: String
    Description: GitHub branch name
    Default: main
  
  GitHubConnectionArn:
    Type: String
    Description: ARN of the GitHub connection from AWS Connector
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the Lambda will be deployed
  
  SubnetIds:
    Type: CommaDelimitedList
    Description: Subnet IDs for Lambda function (comma-separated)
  
  MongoSecretName:
    Type: String
    Default: mongodb/eventsquid
    Description: Name of the secret in Secrets Manager containing MongoDB connection string
  
  MongoDbName:
    Type: String
    Default: eventsquid
    Description: MongoDB database name

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 30

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Policies:
        - PolicyName: CodeBuildServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                  - !Sub arn:aws:s3:::${ArtifactBucket}
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:PutObjectAcl
                  - s3:ListBucket
              - Effect: Allow
                Resource: '*'
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource: '*'
                Action:
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:PassRole
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:GetRolePolicy
              - Effect: Allow
                Resource: '*'
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
              - Effect: Allow
                Resource: '*'
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
              - Effect: Allow
                Resource: '*'
                Action:
                  - apigateway:*
                  - execute-api:*

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineServiceRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                  - !Sub arn:aws:s3:::${ArtifactBucket}
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:PutObjectAcl
                  - s3:ListBucket
              - Effect: Allow
                Resource: '*'
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetProjects
                  - codestar-connections:UseConnection

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucket
            Type: PLAINTEXT
          - Name: VPC_ID
            Value: !Ref VpcId
            Type: PLAINTEXT
          - Name: SUBNET_IDS
            Value: !Join [',', !Ref SubnetIds]
            Type: PLAINTEXT
          - Name: MONGO_SECRET_NAME
            Value: !Ref MongoSecretName
            Type: PLAINTEXT
          - Name: MONGO_DB_NAME
            Value: !Ref MongoDbName
            Type: PLAINTEXT
          - Name: AWS_REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 24
              commands:
                - echo "Installing dependencies..."
                - npm ci
            pre_build:
              commands:
                - echo "Running tests..."
                - npm test || true
            build:
              commands:
                - echo "Packaging Lambda function..."
                - npm install --production
                - zip -r function.zip . -x '*.git*' -x '*.zip' -x 'node_modules/.cache/*' -x '*.md' -x '.github/*' -x 'cloudformation/*' -x '*.test.js' -x '.eslintrc*'
                - echo "Determining environment from branch..."
                - export BRANCH_NAME=${CODEBUILD_SOURCE_VERSION#refs/heads/}
                - echo "Branch: $BRANCH_NAME"
                - '[ "$BRANCH_NAME" = "main" ] && export ENVIRONMENT=prod || ([ "$BRANCH_NAME" = "develop" ] && export ENVIRONMENT=staging || export ENVIRONMENT=dev)'
                - echo "Environment: $ENVIRONMENT"
                - echo "Verifying AWS credentials..."
                - aws sts get-caller-identity || echo "Warning: Could not verify AWS credentials"
                - echo "Deploying CloudFormation stack..."
                - aws cloudformation deploy --template-file cloudformation/template.yaml --stack-name eventsquid-private-api --parameter-overrides Environment=${ENVIRONMENT} VpcId=${VPC_ID} SubnetIds=${SUBNET_IDS} MongoSecretName=${MONGO_SECRET_NAME} MongoDbName=${MONGO_DB_NAME} --capabilities CAPABILITY_NAMED_IAM --region ${AWS_REGION}
                - echo "Updating Lambda function code..."
                - aws lambda update-function-code --function-name eventsquid-private-api --zip-file fileb://function.zip --region ${AWS_REGION}
                - echo "Updating Lambda function configuration..."
                - aws lambda update-function-configuration --function-name eventsquid-private-api --environment Variables="{NODE_ENV=${ENVIRONMENT},MONGO_SECRET_NAME=${MONGO_SECRET_NAME},MONGO_DB_NAME=${MONGO_DB_NAME}}" --region ${AWS_REGION}
          artifacts:
            files:
              - function.zip
              - '**/*'

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Sub ${GitHubOwner}/${GitHubRepo}
                BranchName: !Ref GitHubBranch
              OutputArtifacts:
                - Name: SourceCode
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildOutput

Outputs:
  PipelineURL:
    Description: CodePipeline URL
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
  PipelineName:
    Description: CodePipeline Name
    Value: !Ref Pipeline
  ArtifactBucketName:
    Description: S3 Bucket for artifacts
    Value: !Ref ArtifactBucket
  BuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref BuildProject

