AWSTemplateFormatVersion: '2010-09-09'
Description: 'EventSquid API - Lambda function with API Gateway for private VPC access'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name

  VpcId:
    Type: String
    Description: VPC ID where the Lambda will run

  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs for the Lambda VPC config

  MongoSecretName:
    Type: String
    Default: mongodb/eventsquid
    Description: Name of the MongoDB secret in AWS Secrets Manager

  MongoDbName:
    Type: String
    Default: eventsquid
    Description: Name of the MongoDB database

  ErrorNotificationEmail:
    Type: String
    Default: ''
    Description: Email address to receive error notifications (optional, leave empty to skip email subscription)

Conditions:
  HasEmail: !Not [!Equals [!Ref ErrorNotificationEmail, '']]

Resources:
  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub eventsquid-private-api-lambda-role-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mongodb/*'
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:primary-mssql/*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/eventsquid-private-api:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/apigateway/eventsquid-private-api:*'

  # Use existing security groups from working Lambda
  # sg-277a3b5e (default/redis) and sg-d087f8ac (SquidSQL/SQUID App Servers)
  # These security groups already have proper egress rules configured
  # Note: VPC endpoints for Secrets Manager and CloudWatch Logs already exist in the VPC

  # Lambda Function
  # Note: Initial deployment uses placeholder code
  # After first deployment, use GitHub Actions or AWS CLI to update with actual code
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub eventsquid-private-api-${Environment}
      Runtime: nodejs24.x
      Handler: src/handler.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            return {
              statusCode: 200,
              body: JSON.stringify({ 
                message: 'Placeholder - deploy actual code via GitHub Actions or AWS CLI',
                note: 'See README.md for deployment instructions'
              })
            };
          };
      Timeout: 60
      MemorySize: 1024  # Increased for production: supports VPC, multiple DB connections, and large codebase
      Environment:
        Variables:
          NODE_ENV: !Ref Environment
          MONGO_SECRET_NAME: !Ref MongoSecretName
          MONGO_DB_NAME: !Ref MongoDbName
          ERROR_SNS_TOPIC_ARN: !Ref ErrorNotificationTopic
      VpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds:
          - sg-277a3b5e  # Use existing security group from working Lambda
          - sg-d087f8ac   # Use existing security group from working Lambda
      ReservedConcurrentExecutions: 10

  # API Gateway - HTTP API (public access via route authorization)
  # Note: CORS is handled by Lambda, not API Gateway, to ensure headers are always present
  ApiGatewayRestApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: eventsquid-private-api
      ProtocolType: HTTP
      Description: EventSquid API Gateway

  # API Gateway Integration
  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiGatewayRestApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:eventsquid-private-api-${Environment}:live-${Environment}/invocations'
      PayloadFormatVersion: '2.0'

  # API Gateway Route - Catch all
  # AuthorizationType: NONE allows public access (no authentication required)
  # Note: OPTIONS requests are handled automatically by API Gateway CORS configuration
  # Do NOT create explicit OPTIONS routes - let API Gateway handle them
  ApiGatewayRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiGatewayRestApi
      RouteKey: '$default'
      AuthorizationType: NONE
      Target: !Sub 'integrations/${ApiGatewayIntegration}'

  # API Gateway Stage
  ApiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ApiGatewayRestApi
      StageName: !Ref Environment
      AutoDeploy: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50
      AccessLogSettings:
        # Reference existing log group (created automatically by API Gateway or manually)
        DestinationArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:API-Gateway-Execution-Logs_${ApiGatewayRestApi}/${Environment}'
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","requestTime":"$context.requestTime","httpMethod":"$context.httpMethod","routeKey":"$context.routeKey","status":$context.status,"protocol":"$context.protocol","responseLength":$context.responseLength,"error":{"message":"$context.error.message","messageString":"$context.error.messageString"},"integration":{"status":"$context.integration.status","error":"$context.integration.error","latency":"$context.integration.latency","requestId":"$context.integration.requestId"},"authorizer":{"error":"$context.authorizer.error","latency":"$context.authorizer.latency","requestId":"$context.authorizer.requestId","status":"$context.authorizer.status"}}'

  # Lambda Permission for API Gateway
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*'

  # CloudWatch Log Group for Lambda
  # Note: Lambda automatically creates this if it doesn't exist, but we define it here for retention policy
  # If it already exists, CloudFormation will update it rather than fail
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub '/aws/lambda/eventsquid-private-api-${Environment}'
      RetentionInDays: 14

  # SNS Topic for Error Notifications
  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub eventsquid-private-api-errors-${Environment}
      DisplayName: EventSquid Private API Errors
      Tags:
        - Key: Environment
          Value: !Ref Environment

  # Email Subscription (optional - only if email is provided)
  ErrorNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      TopicArn: !Ref ErrorNotificationTopic
      Protocol: email
      Endpoint: !Ref ErrorNotificationEmail

  # IAM Policy for Lambda to publish to SNS
  LambdaSNSPublishPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaSNSPublishPolicy
      Roles:
        - !Ref LambdaExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Ref ErrorNotificationTopic


Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
    Export:
      Name: !Sub eventsquid-private-api-url-${Environment}

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub eventsquid-private-api-lambda-arn-${Environment}

  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub eventsquid-private-api-lambda-name-${Environment}

  ErrorNotificationTopicArn:
    Description: SNS Topic ARN for error notifications
    Value: !Ref ErrorNotificationTopic
    Export:
      Name: !Sub eventsquid-private-api-error-topic-arn-${Environment}

